solver:
  candidate:
    k: 24
    use_knn: true
  features:
    kd_backend: "auto"      # auto | sklearn | scipy | numpy  
    max_threads_per_lib: 1  # clamp BLAS/OpenMP during KD ops
  zones:
    agents_per_zone: 4
    adaptive_overlap:
      enabled: true
      portal_pct: 2.0
  bees:
    time_budget_s: 1.0
  local_search:
    kick_period_moves: 400
    use_or_opt: true
    stall_windows: 2
    three_opt_lite: true
    tri_budget: 1000
  scouting:
    dynamic:
      enabled: true
      no_improve_s: 8.0
      max_restarts_per_seed: 3
      polish_time_s: 0.6
  termination:
    wall_time_s: 30.0

integrator:
  method: "ucr"
  ucr:
    parents: 4
    children_per_pair: 1
    repair_budget_ms: 30