paths:
  tsplib_dir: "data/tsplib"
  results_dir: "results"
  instances_file: "benchmarks/instances.txt"

solver:
  candidate:
    k: 30
    use_delaunay: true
    use_knn: true
    use_alpha_near: false
  zones:
    method: "kmeans"
    overlap_pct: 0.15
    target_zone_size: 200
    agents_per_zone: 4
  bees:
    scout_fraction: 0.15
    stagnation_moves: 300
    levy_jump_prob: 0.10
    max_improving_moves: 800
    time_budget_s: 2.0
  local_search:
    use_lk: false
    max_k: 5
    double_bridge: true
    kick_period_moves: 300
  integrator:
    mode: "popmusic"
    merge_edge_cap_per_node: 12
    parents_per_round: 10
    rounds: 3
  ehm:
    smoothing_eps: 0.03
    max_edges_per_node: 16
  learning:
    enabled: false
    warmup_tours: 100
    model: "gbdt"
    feature_set: ["distance","delaunay_adj","degree","alpha_nearness","pi_penalty"]
  termination:
    wall_time_s: 60
    target_gap_pct: 0.5

benchmark:
  runs: 5
  threads: 1
  ttt_thresholds_pct: [1.0, 0.5, 0.1]
  seed_list: [0,1,2,3,4]
